from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from api.dependencies import get_db
from services.example_service import ExampleService
from schemas.example import ExampleResponse, CreateExampleRequest, UpdateExampleRequest

# NOTE: some of this file was generated by AI but it's simply a template for future code

router = APIRouter(prefix="/example")


@router.get("/", response_model=list[ExampleResponse])
def get_examples(db: Session = Depends(get_db)):
    return ExampleService.get_all(db)


@router.get("/{id}", response_model=ExampleResponse)
def get_example(id: int, db: Session = Depends(get_db)):
    return ExampleService.get(db, id)


@router.post("/", response_model=ExampleResponse)
def create_example(payload: CreateExampleRequest, db: Session = Depends(get_db)):
    return ExampleService.create(db, payload)


@router.put("/{id}", response_model=ExampleResponse)
def update_example(id: int, payload: UpdateExampleRequest, db: Session = Depends(get_db)):
    return ExampleService.update(db, id, payload)


@router.delete("/{id}")
def delete_example(id: int, db: Session = Depends(get_db)):
    return {"success": ExampleService.delete(db, id)}
